---
-   name: Get facts by tags
    azure_rm_virtualmachine_info:
        resource_group: "{{ resource_group }}"
    delegate_to: localhost
    register: az_facts



-   name: Display all variables/facts known for a host
    debug:
        var: az_facts



-   name: add instance to hosts
    add_host:
        name: "{{ item.tags.PublicIP }}"
        groups:
        - "{{ item.name[0:-3] }}" # instance name from provision_instances/vars/main.yml
        - "{{ item.tags.Type }}" # instance type from provision_instances/vars/main.yml
        - devops
        # the keys below are dynamic and can have any name and value. A way to add data to the host which can be read later
        iname: "{{ item.name[0:-3] }}"
        itype: "{{ item.tags.Type }}"
    with_items: "{{ az_facts.vms }}"
    when: item.tags.PublicIP is defined and item.power_state == "running"


-   name: Display all groups
    debug:
        msg: "All groups: {{ groups.keys() | list }}"




-   name: Display all variables/facts known for a host
    debug:
        var: hostvars

- name: Initialize domain list with base domain
  set_fact:
    all_certbot_domains: ["{{ domain_name }}"]

- name: Add appserver subdomains to certbot domain list
  set_fact:
    all_certbot_domains: "{{ all_certbot_domains + ['appserver' ~ item ~ '.' ~ domain_name] }}"
  with_sequence: start=1 end={{ groups['appserver'] | length }}
  when: groups['appserver'] is defined and groups['appserver'] | length > 0

- name: Show all certbot domains
  debug:
    var: all_certbot_domains