---
# Here you can add variables that will be available for all hosts.
ansible_python_interpreter: "python3"

region: northeurope
resource_group: "DIDA-AHAI22-DV1673-H24-LP2"
domain_name: "ahmadasili.tech"

admin_email: "ahai22@student.bth.se"

vmtags:
    StudentId: "ahai22"

pub_ssh_key_location: '~/.ssh/microblog_azure.pub'


server_user: "deploy"
server_user_pass: "test" # change me
server_user_groups:
    -   sudo


secret_key: its_a_secret
mysql_user: microblog
mysql_password: heejheeej
mysql_db: microblog