- name: Install Nginx
  apt:
    name: nginx
    update_cache: true
    state: present

- name: Configure Nginx reverse proxy
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart Nginx

- name: Ensure Nginx is running
  systemd:
    name: nginx
    state: started
    enabled: true
