- name: Install Docker package
  apt:
    name: docker.io
    state: present
    update_cache: true

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: true
    state: started

- name: Install pip for Python 3
  apt:
    name: python3-pip
    state: present
    update_cache: true

- name: Install Docker SDK for Python
  pip:
    name: docker
    executable: pip3
